# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gate_view_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gate_view_control(object):
    def setupUi(self, gate_view_control):
        gate_view_control.setObjectName("gate_view_control")
        gate_view_control.resize(286, 227)
        self.horizontalLayout = QtWidgets.QHBoxLayout(gate_view_control)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.group_gate = QtWidgets.QGroupBox(gate_view_control)
        self.group_gate.setObjectName("group_gate")
        self.formLayout = QtWidgets.QFormLayout(self.group_gate)
        self.formLayout.setObjectName("formLayout")
        self.l_room_a = QtWidgets.QLabel(self.group_gate)
        self.l_room_a.setObjectName("l_room_a")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l_room_a)
        self.l_room_b = QtWidgets.QLabel(self.group_gate)
        self.l_room_b.setObjectName("l_room_b")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l_room_b)
        self.l_com_servi = QtWidgets.QLabel(self.group_gate)
        self.l_com_servi.setObjectName("l_com_servi")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.l_com_servi)
        self.l_com_arduino = QtWidgets.QLabel(self.group_gate)
        self.l_com_arduino.setObjectName("l_com_arduino")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.l_com_arduino)
        self.l_com_rfid = QtWidgets.QLabel(self.group_gate)
        self.l_com_rfid.setObjectName("l_com_rfid")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.l_com_rfid)
        self.l_weight_factor = QtWidgets.QLabel(self.group_gate)
        self.l_weight_factor.setObjectName("l_weight_factor")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.l_weight_factor)
        self.l_mouse_average = QtWidgets.QLabel(self.group_gate)
        self.l_mouse_average.setObjectName("l_mouse_average")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.l_mouse_average)
        self.led_room_a = QtWidgets.QLineEdit(self.group_gate)
        self.led_room_a.setEnabled(False)
        self.led_room_a.setObjectName("led_room_a")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.led_room_a)
        self.led_room_b = QtWidgets.QLineEdit(self.group_gate)
        self.led_room_b.setEnabled(False)
        self.led_room_b.setObjectName("led_room_b")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.led_room_b)
        self.led_com_servo = QtWidgets.QLineEdit(self.group_gate)
        self.led_com_servo.setEnabled(False)
        self.led_com_servo.setObjectName("led_com_servo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.led_com_servo)
        self.led_com_arduino = QtWidgets.QLineEdit(self.group_gate)
        self.led_com_arduino.setEnabled(False)
        self.led_com_arduino.setObjectName("led_com_arduino")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.led_com_arduino)
        self.led_com_rfid = QtWidgets.QLineEdit(self.group_gate)
        self.led_com_rfid.setEnabled(False)
        self.led_com_rfid.setObjectName("led_com_rfid")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.led_com_rfid)
        self.led_weight_factor = QtWidgets.QLineEdit(self.group_gate)
        self.led_weight_factor.setEnabled(False)
        self.led_weight_factor.setObjectName("led_weight_factor")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.led_weight_factor)
        self.led_mouse_average = QtWidgets.QLineEdit(self.group_gate)
        self.led_mouse_average.setEnabled(False)
        self.led_mouse_average.setObjectName("led_mouse_average")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.led_mouse_average)
        self.horizontalLayout.addWidget(self.group_gate)

        self.retranslateUi(gate_view_control)
        QtCore.QMetaObject.connectSlotsByName(gate_view_control)

    def retranslateUi(self, gate_view_control):
        _translate = QtCore.QCoreApplication.translate
        gate_view_control.setWindowTitle(_translate("gate_view_control", "Form"))
        self.group_gate.setTitle(_translate("gate_view_control", "Gate : Gate 1"))
        self.l_room_a.setText(_translate("gate_view_control", "Room a"))
        self.l_room_b.setText(_translate("gate_view_control", "Room b"))
        self.l_com_servi.setText(_translate("gate_view_control", "COM Servo"))
        self.l_com_arduino.setText(_translate("gate_view_control", "COM Arduino"))
        self.l_com_rfid.setText(_translate("gate_view_control", "COM RFID"))
        self.l_weight_factor.setText(_translate("gate_view_control", "Weight factor"))
        self.l_mouse_average.setText(_translate("gate_view_control", "Mouse average weight"))
