# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transition_doors_view_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_transition_doors(object):
    def setupUi(self, transition_doors):
        transition_doors.setObjectName("transition_doors")
        transition_doors.resize(296, 143)
        self.gridLayout_2 = QtWidgets.QGridLayout(transition_doors)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(transition_doors)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_transition = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_transition.setFont(font)
        self.lbl_transition.setObjectName("lbl_transition")
        self.verticalLayout.addWidget(self.lbl_transition)
        self.lbl_restricted = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_restricted.setFont(font)
        self.lbl_restricted.setObjectName("lbl_restricted")
        self.verticalLayout.addWidget(self.lbl_restricted)
        self.layout_doors = QtWidgets.QHBoxLayout()
        self.layout_doors.setObjectName("layout_doors")
        self.verticalLayout.addLayout(self.layout_doors)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_nb_mice = QtWidgets.QLabel(transition_doors)
        self.lbl_nb_mice.setObjectName("lbl_nb_mice")
        self.horizontalLayout.addWidget(self.lbl_nb_mice)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_start = QtWidgets.QPushButton(transition_doors)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_2.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(transition_doors)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_2.addWidget(self.btn_stop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)

        self.retranslateUi(transition_doors)
        QtCore.QMetaObject.connectSlotsByName(transition_doors)

    def retranslateUi(self, transition_doors):
        _translate = QtCore.QCoreApplication.translate
        transition_doors.setWindowTitle(_translate("transition_doors", "Form"))
        self.groupBox_2.setTitle(_translate("transition_doors", "Transition doors"))
        self.lbl_transition.setText(_translate("transition_doors", "Transition between \"PARADISE\" and\" HELL\""))
        self.lbl_restricted.setText(_translate("transition_doors", "Restricted room : \"PARADISE\" with max mice set to 3"))
        self.lbl_nb_mice.setText(_translate("transition_doors", "Nb mice in limited room : 0"))
        self.btn_start.setText(_translate("transition_doors", "Start"))
        self.btn_stop.setText(_translate("transition_doors", "Stop"))
