name: sas_door
channels:
  - defaults
dependencies:
  - python=3.8.*
  - numpy=1.23.*
  - pyqt=5.*
  - pyyaml=6.*
  - matplotlib=3.7.*
  - pip
  - pip:
    - git+https://nicknolt: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@github.com/nicknolt/mqtt_device
    - lxml==4.9.*
    - dependency-injector==4.41.0
    - dynamixel-sdk==3.7.31
    - singleton-decorator==1.0.0

